import { Research } from "./types";

export const RESEARCH_TREE: Research[] = [
  {
    id: "basic_firewall",
    name: "Advanced Firewall Rules",
    description: "Deploy next-generation firewall with deep packet inspection",
    category: "prevention",
    cost: 8000,
    duration: 15,
    unlocked: false,
    researching: false,
    progress: 0,
    effect: { firewallStrength: 15 },
    prerequisites: [],
  },
  {
    id: "employee_training",
    name: "Security Awareness Program",
    description: "Comprehensive phishing and social engineering training for all staff",
    category: "prevention",
    cost: 5000,
    duration: 10,
    unlocked: false,
    researching: false,
    progress: 0,
    effect: { employeeAwareness: 20 },
    prerequisites: [],
  },
  {
    id: "patch_management",
    name: "Automated Patch Management",
    description: "Deploy automated patching system for critical vulnerabilities",
    category: "prevention",
    cost: 12000,
    duration: 20,
    unlocked: false,
    researching: false,
    progress: 0,
    effect: { patchLevel: 20 },
    prerequisites: [],
  },
  {
    id: "siem_basic",
    name: "SIEM Deployment",
    description: "Security Information and Event Management system for log correlation",
    category: "detection",
    cost: 15000,
    duration: 25,
    unlocked: false,
    researching: false,
    progress: 0,
    effect: { aiDetectionLevel: 10, securityMaturity: 5 },
    prerequisites: [],
  },
  {
    id: "threat_intel",
    name: "Threat Intelligence Feed",
    description: "Subscribe to premium threat intelligence feeds for early warning",
    category: "detection",
    cost: 10000,
    duration: 12,
    unlocked: false,
    researching: false,
    progress: 0,
    effect: { threatIntelligence: 20 },
    prerequisites: ["siem_basic"],
  },
  {
    id: "incident_response",
    name: "Incident Response Plan",
    description: "Develop and drill a comprehensive incident response procedure",
    category: "response",
    cost: 8000,
    duration: 18,
    unlocked: false,
    researching: false,
    progress: 0,
    effect: { incidentResponseTime: -3, securityMaturity: 10 },
    prerequisites: [],
  },
  {
    id: "encryption_suite",
    name: "Enterprise Encryption Suite",
    description: "End-to-end encryption for all data at rest and in transit",
    category: "prevention",
    cost: 18000,
    duration: 22,
    unlocked: false,
    researching: false,
    progress: 0,
    effect: { dataEncryption: 25 },
    prerequisites: ["basic_firewall"],
  },
  {
    id: "ai_anomaly",
    name: "AI Anomaly Detection",
    description: "Machine learning model for detecting unusual network behavior",
    category: "ai",
    cost: 25000,
    duration: 30,
    unlocked: false,
    researching: false,
    progress: 0,
    effect: { aiDetectionLevel: 25, securityMaturity: 10 },
    prerequisites: ["siem_basic"],
  },
  {
    id: "ai_behavioral",
    name: "AI Behavioral Analysis",
    description: "Deep learning system for employee and entity behavior analytics",
    category: "ai",
    cost: 30000,
    duration: 35,
    unlocked: false,
    researching: false,
    progress: 0,
    effect: { aiDetectionLevel: 20, employeeAwareness: 10 },
    prerequisites: ["ai_anomaly", "employee_training"],
  },
  {
    id: "zero_trust",
    name: "Zero Trust Architecture",
    description: "Implement zero trust network model - never trust, always verify",
    category: "prevention",
    cost: 35000,
    duration: 40,
    unlocked: false,
    researching: false,
    progress: 0,
    effect: { firewallStrength: 20, securityMaturity: 15, dataEncryption: 10 },
    prerequisites: ["encryption_suite", "basic_firewall"],
  },
  {
    id: "red_team",
    name: "Red Team Operations",
    description: "Internal red team for continuous penetration testing",
    category: "response",
    cost: 20000,
    duration: 28,
    unlocked: false,
    researching: false,
    progress: 0,
    effect: { securityMaturity: 15, patchLevel: 10, threatIntelligence: 10 },
    prerequisites: ["incident_response", "threat_intel"],
  },
  {
    id: "ai_predictive",
    name: "Predictive Threat Modeling",
    description: "AI system that predicts attacks before they happen using pattern analysis",
    category: "ai",
    cost: 40000,
    duration: 45,
    unlocked: false,
    researching: false,
    progress: 0,
    effect: { aiDetectionLevel: 30, threatIntelligence: 20, securityMaturity: 10 },
    prerequisites: ["ai_behavioral", "red_team"],
  },
];
